layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

  
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

include: 
  - ".well-known"

topics:
  - name: Web
    web_url: https://github.com/topics/web

  - name: Security

  - name: Go
    web_url: https://github.com/topics/golang

  - name: Android
